name: Github Action push
on:
  push:
    branches: [main]
  pull-request:
    branches: [main]
jobs:
  Students:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Fazendo o CI!!!!!"
      - name: Checkout repository code
        uses: actions/checkout@v3
        - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
				#precisamos criar um .env file por que o nosso está no gitignore
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "123456"
          envkey_POSTGRES_DB: "banco"
          envkey_DATABASE_URL: "postgres://postgres:123456@db:5432/banco"
          file_name: .env.test
      - name: Run tests
        run: npm test
      - name: Build
        run: npm i && npm run build
