name: Github Action push
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  Students:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Fazendo o CI!!!!!"
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: 'postgres'
          envkey_POSTGRES_PASSWORD: 'postgres'
          envkey_POSTGRES_DB: 'students__tests'
          envkey_DATABASE_URL: 'postgres://postgres:postgres@db_postgres:5432/students__tests'
          file_name: .env.test
      - name: Run tests
        run: npm test
      - name: Build
        run: npm i && npm run build
